### ISSUE TITLE
Traceback (most recent call last):   File "cloud2butt.py", line 32, in processHttpMessage     headers, body = self.getResponseHeadersAndBody(content) TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by minanagehsalalma** [everythingishacked/burpsuite-custom-extension#1]
![image](https://user-images.githubusercontent.com/20546638/168723369-8f728aa7-cc9d-4a2d-9736-72a2b5249292.png)

**Comment by everythingishacked** [comment]
Sounds like you probably got empty `content` that couldn't be parsed. Hard to say without more info.

**Comment by minanagehsalalma** [comment]
> Sounds like you probably got empty `content` that couldn't be parsed. Hard to say without more info.

The fix is that the code needs to check is None: or not before doing and process on the requests

**Comment by everythingishacked** [comment]
Ah that makes sense! Not sure why content would be `None`, but it's a good check to have in there regardless. Feel free to submit a PR for that update and I'll get it merged.

**Comment by minanagehsalalma** [comment]
@everythingishacked done
